name: Windows

on:
  push:
    branches: [main, dev]
    tags: ['v*']  # This now triggers the build on Tags too!
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: lukka/get-cmake@latest
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Create GitHub Release
        # Only run this step if we pushed a tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build/rux.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
